[package]
name = "server"
edition.workspace = true
version.workspace = true
authors.workspace = true

[[bin]]
path = "src/main.rs"
name = "server"
doc = true
plugin = false
proc-macro = false
harness = true
required-features = []

[dependencies]
tokio = "1.38.0"
tonic = "0.11.0"
